[project]
name = "git-stargazer"
version = "0.1.0"
description = "Generate activity reports for starred GitHub repositories"
requires-python = ">=3.13"

dependencies = [
    "httpx",
    "litellm",
]

[dependency-groups]
dev = [
    "gitpython>=3.1.44",
]
