name: Generate Starred Repos Report

on:
  schedule:
    - cron: '30 22 * * *'  # Run daily at 6:30am UTC+8
  workflow_dispatch:  # Allow manual trigger
  # push:
  #   branches:
  #     - master

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
    
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"
    
    - name: Install dependencies
      run: |
        uv sync --all-extras --dev

    - name: Restore commit timestamps cache
      uses: actions/cache/restore@v4
      with:
        path: commit_timestamps.json
        key: commit-timestamps-${{ github.run_id }}
        restore-keys: |
          commit-timestamps-

    - name: Restore report cache
      uses: actions/cache/restore@v4
      with:
        path: reports/
        key: report-cache-${{ github.run_id }}
        restore-keys: |
          report-cache-
    
    - name: Set TODAY variable
      id: set_date
      run: |
        echo "TODAY=$(TZ=Asia/Shanghai date +'%Y-%m-%d')" >> $GITHUB_ENV
        echo "TODAY=$(TZ=Asia/Shanghai date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Generate report
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}  # required
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}  # required
        REPO_LIMIT: ${{ vars.REPO_LIMIT }}  # optional
        EMPTY_REPO_CONSECUTIVE_LIMIT: ${{ vars.EMPTY_REPO_CONSECUTIVE_LIMIT }}  # optional
      run: uv run src/main.py
      id: generate_report
    
    - name: Save commit timestamps cache
      uses: actions/cache/save@v4
      with:
        path: commit_timestamps.json
        key: commit-timestamps-${{ github.run_id }}
    
    - name: Save report cache
      uses: actions/cache/save@v4
      with:
        path: reports/
        key: report-cache-${{ github.run_id }}
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        name: "Activity Report ${{ env.TODAY }}"
        tag_name: ${{ env.TODAY }}
        body_path: ${{ steps.generate_report.outputs.report_file }}
        files: |
          ${{ steps.generate_report.outputs.report_file }}
          ${{ steps.generate_report.outputs.report_json_file }}

    - name: Create latest symbolic link
      run: |
        cp ${{ steps.generate_report.outputs.report_json_file }} reports/recent_commits_latest.json

    - name: Upload latest report
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        tag_name: latest
        files: |
          reports/recent_commits_latest.json
        prerelease: true
