name: Generate Starred Repos Report

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
    
    - name: Set up Python
      run: uv python install
      with:
        python-version-file: "pyproject.toml"
    
    - name: Install dependencies
      run: |
        uv sync --all-extras --dev

    - name: Restore commit timestamps cache
      uses: actions/cache/restore@v4
      with:
        path: commit_timestamps.json
        key: commit-timestamps-${{ github.run_id }}
        restore-keys: |
          commit-timestamps-
    
    - name: Generate report
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python src/main.py
    
    - name: Save commit timestamps cache
      uses: actions/cache/save@v4
      with:
        path: commit_timestamps.json
        key: commit-timestamps-${{ github.run_id }}
    
    - name: Commit and push report
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add reports/
        git commit -m "Update recent activity report" || exit 0
        git push 