name: Generate Starred Repos Report

on:
  schedule:
    - cron: '0 20 * * *'  # Run daily at 4am UTC+8
  workflow_dispatch:  # Allow manual trigger
  push:
    branches:
      - master

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
    
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"
    
    - name: Install dependencies
      run: |
        uv sync --all-extras --dev

    - name: Restore commit timestamps cache
      uses: actions/cache/restore@v4
      with:
        path: commit_timestamps.json
        key: commit-timestamps-${{ github.run_id }}
        restore-keys: |
          commit-timestamps-

    - name: Restore report cache
      uses: actions/cache/restore@v4
      with:
        path: reports/
        key: report-cache-${{ github.run_id }}
        restore-keys: |
          report-cache-
    
    - name: Set TODAY variable
      id: set_date
      run: |
        echo "TODAY=$(TZ=Asia/Shanghai date +'%Y-%m-%d')" >> $GITHUB_ENV
        echo "TODAY=$(TZ=Asia/Shanghai date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Generate report
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}  # required
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}  # required
        REPO_LIMIT: ${{ vars.REPO_LIMIT }}  # optional
        EMPTY_REPO_CONSECUTIVE_LIMIT: ${{ vars.EMPTY_REPO_CONSECUTIVE_LIMIT }}  # optional
      run: uv run src/main.py
      id: generate_report
    
    - name: Save commit timestamps cache
      uses: actions/cache/save@v4
      with:
        path: commit_timestamps.json
        key: commit-timestamps-${{ github.run_id }}
    
    - name: Save report cache
      uses: actions/cache/save@v4
      with:
        path: reports/
        key: report-cache-${{ github.run_id }}
    
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        TODAY: ${{ env.TODAY }}
      run: |
        DATE=$TODAY
        
        # Delete existing release if it exists
        gh release delete "${DATE}" --yes || true
        
        # Create a new release using the report file content
        gh release create "${DATE}" \
          --title "Activity Report ${DATE}" \
          --notes-file "${{ steps.generate_report.outputs.report_file }}"
